text = """
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed pretium, ante ac adipiscing elementum, mauris odio auctor est, ac dignissim nibh neque eu dui. Duis venenatis nisi massa. Aliquam erat volutpat. Vestibulum vel sem at dolor interdum volutpat. In hac habitasse platea dictumst. Nulla iaculis dictum nisi ac convallis. Nam ut velit ante. Nulla elementum, erat sed varius tincidunt, enim leo condimentum eros, sit amet suscipit enim leo vitae tellus. Sed elementum massa at libero gravida tincidunt. Mauris cursus malesuada nisi, in porttitor nisi pharetra nec. Donec vel leo nec nibh molestie posuere. Donec mi orci, vulputate et sodales quis, tempus rhoncus nibh.

Etiam dolor nunc, tristique eget sagittis a, porttitor at mauris. Cras nisl tortor, fermentum sed interdum nec, sollicitudin sed urna. Aliquam erat volutpat. Integer porttitor velit sed enim congue suscipit. Sed dolor felis, sodales quis volutpat nec, porttitor id ante. Pellentesque sapien dolor, auctor at suscipit adipiscing, pretium id justo. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent eu semper eros. Maecenas ut arcu purus.

Vivamus a pharetra eros. Fusce suscipit nibh et nibh bibendum vitae rhoncus massa iaculis. Praesent at justo et sapien mattis lobortis eu posuere justo. Maecenas facilisis eros at lacus accumsan malesuada. Quisque sed tellus nisi. Sed convallis venenatis magna, et pretium sapien molestie vel. Aenean sed urna quis dui iaculis mattis ut a est. Nam lectus elit, facilisis quis rhoncus sed, rhoncus non ipsum. Aenean ac magna in mi blandit rutrum.

Integer consequat mi ac erat egestas in rhoncus ligula hendrerit. Proin vitae quam quam. Suspendisse eu sapien arcu. Etiam sit amet velit est, nec dignissim libero. Sed consequat sagittis aliquet. Pellentesque sapien ipsum, consectetur et placerat eu, tincidunt at mauris. Aenean blandit tortor ligula, nec rutrum ligula. Integer luctus pharetra quam. Sed eget elit velit. In ornare nibh eu mi vestibulum in convallis erat congue. Sed laoreet purus a tellus porttitor consequat et non neque. Nullam congue nisi id nibh posuere a fermentum arcu lacinia. Integer a lacus sed urna volutpat adipiscing at eget arcu. Nullam a sapien ligula.

Nunc tellus ipsum, luctus sit amet accumsan quis, ultricies quis enim. Aenean bibendum ipsum placerat nisi molestie rhoncus sagittis purus luctus. Vestibulum varius consectetur dui vitae ullamcorper. Ut feugiat varius eros, vitae hendrerit nulla hendrerit dapibus. Integer cursus dui at nulla ultrices elementum. Vestibulum eros ante, congue nec convallis eget, bibendum sit amet est. Fusce dignissim pharetra massa in lobortis. Etiam nisi sem, molestie at congue ac, sagittis ac urna. Maecenas nec purus nisi.
"""